# -*- coding: utf-8 -*-
#
# Configuration setup file for PyRadiomics texture feature extraction.
#
# PyRadiomics version: 2.0.1
#


setting:
  # Relaxing an eventual correlation between features and scanners due to
  # inter-scanner variability.
  normalize: True
  # Distance to neighbour: Specifies the distances between the center voxel and
  # the neighbor, for which angles should be generated. Only affects the GLCM
  # and NGTDM feature classes. The GLSZM and GLRLM feature classes use a fixed
  # distance of 1 (infinity norm) to define neighbours.
  distances: [1]
  # Gray level discretization: 32 bins.
  binWidth: 0.1351010101010101
  # Shifting gray level values > 0 due to normalization as required by some
  # texture features. Shift value is ceiling of average of global max across
  # all CT samples, which is the largest value used in zero-centering for
  # nomralization.
  # NOTE: Requires <int>.
  voxelArrayShift: 3442
  # Value of ROI in mask (is binary).
  label: 1
  # Disable output of additional information from the extraction.
  additionalInfo: False


imageType:
  Original: {}


featureClass:
  glcm:
  glrlm:
  glszm:
  gldm:
  ngtdm:
